# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoReport',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('timestamp', models.BigIntegerField()),
                ('accuracy', models.FloatField()),
                ('deviceId', models.TextField(max_length=30)),
            ],
        ),
    ]
